# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:starter@localhost:5432/hc_rails_starter_development" %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:starter@localhost:5432/hc_rails_starter_test" %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
