default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [realtime, default]
      threads: 4
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>
      polling_interval: 0.1
    - queues: [background, ahoy, uptime]
      threads: 6
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>
    - queues: [active_storage]
      threads: 2
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
