---
authentication: <%= ENV.fetch("SKYLIGHT_AUTHENTICATION", nil) %>

development:
  enabled: false

production:
  enabled: true
  log_file: log/skylight.log

staging:
  enabled: true
  log_file: log/skylight.log
